### PR TITLE
Added more visible buttons

### PR DESCRIPTION
**Pull request by cempack**
Holding buttons :
holding2
holding3
holding1
Not holding buttons :
default
Hope that will be added
I know it's a basic css thing but it will be cool to have

### CODE REVIEW

**Comment by Haeri** [comment]
Hi @cempack 
Thanks for your PR!

This is an interesting request. Do you feel that the buttons are not visible enough? 
In my opinion, everyone who manages to install monolith code intuitively should know that the window control buttons are at the top so I don't think that visibility should be an issue.
But I do agree that introducing a bit of color does look nice. What would you say about a compromise where only the red close button would be permanently visible like this:

Snipaste_2022-05-10_21-18-16

This would also be very much in line with the logo.

Best regards
Haeri

**Comment by cempack** [comment]
First for the question, no the buttons are visible but the thing is that I find them more beautiful when they are colored

  For the design you made in the screenshot, it's pretty cool but it's a "simple editor" and I think consistency is important


Sorry for my english
 cempack

**Comment by Haeri** [comment]
I see what you mean. Ok, we can try to make this work. However, I see 3 issues:
- [ ] 1. It is difficult to see what you changed exactly in the PR, cause the entire file got formatted. Could you remove the formating and only submit your changes (I will do the formatting in a different commit)
- [ ] 2. I don't like how the color gets darker on hover. I would suggest switching it around so from dark to bright on hover.
- [ ] 3. The pin-to-foreground button looks a bit out of place with this change. So I would either have to be removed or adjusted somehow

Snipaste_2022-05-14_01-05-56

**Comment by Haeri** [comment]
I have adjusted the style in the #28 2.2.2 release similar to what you suggested here.

**Pull request closed without merging**
